### ISSUE TITLE
Improve handling of Prepared/Statement for cbqueryx

### ISSUE THREAD

**Issue by brett19** [couchbase/gocbcorex#126]
We added a mechanism to ensure that the Prepared value is cleared from a query before we attempt to execute a preparation.  We should adjust this logic to correctly handle the cases where the user has passed 'Prepared' directly.  We should also add logic to ensure that the Statement has been provided before we attempt to do internal preparation.

**Comment by chvck** [comment]
https://couchbasecloud.atlassian.net/browse/ING-578
