### ISSUE TITLE
Some error handling causes infinite recursion

### ISSUE THREAD

**Issue by brett19** [couchbase/gocbcorex#142]
I ran into a case where range scan creates encoder was generating `{"error": "dispatch error: invalid argument error: one of range and sampling must set"}`, but this counted as a 'DispatchError', which meant that the client orchestrator immediately retried the operation with a different client, but never was successful.

**Comment by chvck** [comment]
Seems that we wrap any error returned from memdx ops as a part of simpleCall in a KvClientDispatchError
