### ISSUE TITLE
Implement a common set of config objects and test utilities to generate them

### ISSUE THREAD

**Issue by brett19** [couchbase/gocbcorex#27]
We currently have many projects that all deal with configurations and have unique structures in each project.  We should consolidate these structures to some common package and provide some utilities to generate them, or alternatively provide some standardized testdata containing them.

**Comment by chvck** [comment]
@brett19 have you now done this?

**Comment by brett19** [comment]
I think the general idea of this was to use something like OpenAPI to describe the structures, and provide some 'examples' to go along with that.  I've got some of it completed, but its nowhere useful yet.

**Comment by brett19** [comment]
https://couchbasecloud.atlassian.net/browse/ING-594
