### ISSUE TITLE
Add LookupIn/MutateIn negative case testing

### ISSUE THREAD

**Issue by brett19** [couchbase/gocbcorex#29]
There are 20+ different cases of errors that can occur for LookupIn or MutateIn.  Resolving this ticket involves looking at all the subdoc-specific status codes we can expect to receive from the server (https://github.com/couchbase/kv_engine/blob/master/include/mcbp/protocol/status.h is a good reference), and then writing test cases to validate that all these cases lead to the expected error behaviour in gocbcorex.

**Comment by chvck** [comment]
Believe this is done.
