### ISSUE TITLE
Validate that non-ssl kv ports are always available

### ISSUE THREAD

**Issue by brett19** [couchbase/gocbcorex#36]
We use the NonSSL KvData ports as part of our unique endpoint identification.  If those values are ever unavailable, it will make the endpoint identification fall apart.  We should validate this can never happen.  If it can, we will be forced to use the SSL endpoints if the NonSSL endpoints are unavailable, which would cause operations to be dropped during a reconfigure.

**Comment by chvck** [comment]
https://couchbasecloud.atlassian.net/browse/ING-581
