### ISSUE TITLE
Add support for connection strings

### ISSUE THREAD

**Issue by brett19** [couchbase/gocbcorex#61]
We currently accept agent configurations using a seed poller list.  We should probably support a more configurable mechanism like connection strings.  Stellar Gateway also has a need to be able to parse the connection strings.  We previously had gocbconnstr as a separate library which then got integrated into gocbcore.  We may need to copy that library to gocbcorex, or alternatively move it back to a canonical repository.

**Comment by brett19** [comment]
We merged a bit of connection string support, but it uses the old gocbconnstr library, we should explicitly decide to use this library, or alternatively move a copy of it into the gocbcorex source tree like gocbcore has done.

**Comment by chvck** [comment]
We have explicitly decided on use of gocbconnstr, and updated that repo accordingly. What more do we need to do here? Support for more properties?

**Comment by chvck** [comment]
@brett19 can we close this or is more functionality required?

**Comment by brett19** [comment]
I'm going to close this as completed as I believe we use connection strings now.  If more is needed in the future, I'm sure a bug will get filed.
