### ISSUE TITLE
Consider, and update, log levels

### ISSUE THREAD

**Issue by chvck** [couchbase/gocbcorex#89]
Zap does not have a more verbose log level than debug. We should probably default to logging at INFO with verbose at DEBUG.

**Comment by iamrajiv** [comment]
@chvck, are you suggesting that we replace the `zap` package with the standard Go `log` package?

**Comment by chvck** [comment]
> @chvck, are you suggesting that we replace the `zap` package with the standard Go `log` package?

No. We're currently typically logging at DEBUG level and this issue is to reconsider that and typically log at INFO with DEBUG being used for more verbose logging. We should also consider having "toggles" for enabling more in depth logging which causes a very large amount of noise. This all needs to also take log redaction into account.

**Comment by chvck** [comment]
Closing this as what we should log will become apparent to us in time.
